---

- name: distribution specific actions
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      skip: true
  when: with_locks_install_deps

- name: create script directory {{ with_locks_script_dir }}
  file:
    path: "{{ with_locks_script_dir }}"
    state: directory
    recurse: yes

- name: copy script {{ with_locks_script_name }}
  copy:
    src: "with-locks.sh"
    dest: "{{ with_locks_script }}"
    mode: '0755'
